# 1. Introduction to Numpy

This tutorial is meant for beginners to start or refresh with the basic methods in NumPy.

In [40]:
import numpy as np  #using alias here

In [41]:
np

<module 'numpy' from '/home/bsarma/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/numpy/__init__.py'>

 # 1.1 Creating Arrays
 
 np.zeros() <br>
 np.ones()  <br>
 np.full()  <br>
 np.array()  <br>
 np.arange() <br>
 np.linspace() <br>

In [42]:
np.zeros(10)  #creates an array of length 10 filled with zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.ones(10)  #creates an array of length 10, filled with one.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.full(10, 2.5)  #creates an array of length 10, filled with 2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [45]:
[1,2,3,5,7,12]  #is a list

[1, 2, 3, 5, 7, 12]

In [46]:
a = np.array([1,2,3,5,7,12])

In [47]:
a[2]  #index of a numpy array start with 0. In MATLAB in starts from 1

3

In [48]:
a

array([ 1,  2,  3,  5,  7, 12])

In [49]:
np.arange(10) #gives an array whose elemensta are filled with integeers from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(3,10) #gives an array whose elements are integers ranging from 3 to 9

array([3, 4, 5, 6, 7, 8, 9])

In [51]:
np.linspace(0,100,11)  #gives an array of length 11 whose elements are equally spaced between 0 and 100

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# 1.2 Multidimensional arrays

In [52]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
n = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

In [54]:
n[0,1]  #gives element at first row and second coloumn

2

In [55]:
n[1]  #gives elements of 2nd row

array([4, 5, 6])

In [56]:
n[:,1]  #gives elements of 2nd column

array([2, 5, 8])

In [57]:
n[:,1]=[0,1,2] #new values are assigned to the 2nd column

In [58]:
n

array([[1, 0, 3],
       [4, 1, 6],
       [7, 2, 9]])

# 1.3 Randomly geneated Arrays

np.random.seed()  <br>
np.random.rand()  <br>
np.random.randn() <br>
np.random.randint()

In [59]:
np.random.seed(2)
100*np.random.rand(5,2) # with standard uniform distribution

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [60]:
np.random.seed(3)
np.random.randn(5,2)  # n for normal distribution

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898],
       [-0.08274148, -0.62700068],
       [-0.04381817, -0.47721803]])

In [61]:
np.random.seed(3)
np.random.randint(low = 0, high= 100, size=(5,2)) #0 is included, 100 is excluded

array([[24,  3],
       [56, 72],
       [ 0, 21],
       [19, 74],
       [41, 10]])

# 1.4 Element wise operations

In [62]:
a = np.arange(5)

In [63]:
a

array([0, 1, 2, 3, 4])

In [64]:
a +1  #addition like this works only with numpy array. not with list. with a list we have to use loop

array([1, 2, 3, 4, 5])

In [65]:
a*2

array([0, 2, 4, 6, 8])

In [66]:
a/100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [67]:
b = (10+(a*2))**2

In [68]:
b

array([100, 144, 196, 256, 324])

In [69]:
a +b # minus, division, mulitiply all works here

array([100, 145, 198, 259, 328])

In [70]:
a >=b

array([False, False, False, False, False])

In [71]:
a[a<b]

array([0, 1, 2, 3, 4])

# 1.5 Summarizing operations

In [72]:
a

array([0, 1, 2, 3, 4])

In [73]:
a.min()

0

In [74]:
a.mean()

2.0

In [75]:
a.std()  #standard deviation

1.4142135623730951

In [76]:
n

array([[1, 0, 3],
       [4, 1, 6],
       [7, 2, 9]])

In [77]:
n.mean() # works for multidimensional arrays as well

3.6666666666666665

# 1.6 Linear Algebra: Vector Operations

In [110]:
a

array([0, 1, 2, 3, 4])

In [111]:
b

array([100, 144, 196, 256, 324])

In [112]:
a+b

array([100, 145, 198, 259, 328])

In [113]:
a * b  # elementwise multiplication

array([   0,  144,  392,  768, 1296])

# 1.6.1 Vector-vector multiplication (dot product)

u.dot(v)

In [114]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [115]:
u.shape

(4,)

In [116]:
v.shape

(4,)

In [117]:
u.shape[0]

4

In [118]:
v.shape[0]

4

In [119]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [120]:
vector_vector_multiplication(u,v)

14.0

In [121]:
u.dot(v)   #dot product between two vectors

14

In [122]:
v.dot(u)  #gives same result as u.dot(v)

14

# 1.6.2 Matrix-vector multiplication

In [123]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])                               # a 3x4 matrix 

In [124]:
U.shape

(3, 4)

In [125]:
U.shape[1]   # number of cols in U

4

In [126]:
def matrix_vector_multiplication(U,v):   #Look into the function
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i]= vector_vector_multiplication(U[i],v)
    
    return result 

In [127]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [128]:
U.dot(v)  #matrix-vector multiplication

array([14,  5,  5])

# 1.6.3 Matrix-matrix multiplication

In [129]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])                             # a 4x3 matrix

In [98]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1]== V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:,i]
        Uvi= matrix_vector_multiplication(U, vi)
        result[:,i] =  Uvi
        
    return result

In [99]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [100]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# 1.7 Linear Algebra: Identity matrix I 

In [130]:
I = np.eye(3)

In [102]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
V   # a 4x3 matrix

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [104]:
V.shape

(4, 3)

In [105]:
W = V.dot(I)
W

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [106]:
W ==V  #multiplying a matrix with an Identity matrix doesn't change the matrix

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 1.8 Linear algebra: Inverse Matrix

np.linalg.inv()

In [131]:
Vs = V[[0,1,2]]  #we select first 3 rows of V to have a square matrix
Vs               # For a matrix to be invertible, 1. it has to be a square matrix and 2. its determinanat!=0

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [132]:
Vs_inv= np.linalg.inv(Vs) 

In [133]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

### End of Introduction to NumPy