# Introduction to Numpy

In [112]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/bsarma/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/numpy/__init__.py'>

 # Creating Arrays

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
[1,2,3,5,7,12]

[1, 2, 3, 5, 7, 12]

In [16]:
a = np.array([1,2,3,5,7,12])

In [18]:
a[2]

3

In [20]:
a

array([ 1,  2,  3,  5,  7, 12])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multidimensional arrays

In [34]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
n = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

In [38]:
n[0,1]

2

In [40]:
n[1]

array([4, 5, 6])

In [42]:
n[:,1]

array([2, 5, 8])

In [46]:
n[:,1]=[0,1,2]

In [48]:
n

array([[1, 0, 3],
       [4, 1, 6],
       [7, 2, 9]])

# Randomly geneated Arrays

In [69]:
np.random.seed(2)
100*np.random.rand(5,2) # with standard uniform distribution

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [70]:
np.random.seed(3)
np.random.randn(5,2)  # n for normal distribution

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898],
       [-0.08274148, -0.62700068],
       [-0.04381817, -0.47721803]])

In [72]:
np.random.seed(3)
np.random.randint(low = 0, high= 100, size=(5,2)) #0 is included, 100 is excluded

array([[24,  3],
       [56, 72],
       [ 0, 21],
       [19, 74],
       [41, 10]])

# Element wise operations

In [74]:
a = np.arange(5)

In [76]:
a

array([0, 1, 2, 3, 4])

In [78]:
a +1  #addition like this works only with numpy array. not with list. with a list we have to use loop

array([1, 2, 3, 4, 5])

In [79]:
a*2

array([0, 2, 4, 6, 8])

In [81]:
a/100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [84]:
b = (10+(a*2))**2

In [87]:
b

array([100, 144, 196, 256, 324])

In [90]:
a +b # minus, division, mulitiply all works here

array([100, 145, 198, 259, 328])

In [93]:
a >=b

array([False, False, False, False, False])

In [102]:
a[a<b]

array([0, 1, 2, 3, 4])

# Summarizing operations

In [104]:
a

array([0, 1, 2, 3, 4])

In [103]:
a.min()

0

In [105]:
a.mean()

2.0

In [107]:
a.std()  #standard deviation

1.4142135623730951

In [109]:
n

array([[1, 0, 3],
       [4, 1, 6],
       [7, 2, 9]])

In [111]:
n.mean() # works for multidimensional arrays as well

3.6666666666666665